// GENERATED by scripts/import-beanie-images.ts — do not edit entries by hand.
//
// Maps beaniePhotoKey(name) → a locally hosted catalogue image for /database
// entries that have no marketplace photo yet. Every entry carries its source
// and license so attribution stays auditable (rendered at /database/credits).
//
// Policy: only properly licensed images enter this map — openly licensed
// sources (e.g. Wikimedia Commons CC files, with credit) or photos we own.
// The importer refuses rows without a license + credit. Marketplace listing
// photos always take priority over these at render time.

export type CatalogueImage = {
  /** Local path under public/, e.g. "/beanie-images/peanut.webp" */
  src: string;
  /** Where the original came from (e.g. a Wikimedia Commons file page). */
  sourceUrl: string;
  /** License short name, e.g. "CC BY-SA 4.0" or "Own work". */
  license: string;
  /** Attribution line (required by CC licenses). */
  credit: string;
};

export const CATALOGUE_IMAGES: Record<string, CatalogueImage> = {};
