// In-memory sample data. Used for local browsing before Neon is connected,
// and as the source for `npm run db:seed` once it is.

import type { Category, Listing, Store } from "./types";

export const categories: Category[] = [
  { id: "cat-clothing", slug: "clothing", name: "Vintage Clothing", sort: 1 },
  { id: "cat-shoes", slug: "shoes", name: "Shoes", sort: 2 },
  { id: "cat-accessories", slug: "accessories", name: "Accessories", sort: 3 },
  { id: "cat-memorabilia", slug: "memorabilia", name: "Sports Memorabilia", sort: 4 },
  { id: "cat-collectables", slug: "collectables", name: "Collectables", sort: 5 },
];

export const stores: Store[] = [
  {
    id: "store-attic",
    slug: "the-attic",
    name: "The Attic",
    tagline: "Curated vintage from decades past",
    description:
      "A hand-picked collection of vintage clothing and rare finds, sourced from estate sales across the country.",
    theme: {
      primary: "#b45309",
      accent: "#f59e0b",
      banner_url: null,
      logo_url: null,
      layout: "grid",
    },
  },
  {
    id: "store-sole",
    slug: "sole-society",
    name: "Sole Society",
    tagline: "Sneakers & vintage kicks",
    description: "Deadstock, rare, and well-loved footwear for collectors and wearers alike.",
    theme: {
      primary: "#1d4ed8",
      accent: "#06b6d4",
      banner_url: null,
      logo_url: null,
      layout: "grid",
    },
  },
  {
    id: "store-dugout",
    slug: "the-dugout",
    name: "The Dugout",
    tagline: "Sports history you can hold",
    description: "Authenticated memorabilia, cards, and game-worn gear from every era.",
    theme: {
      primary: "#15803d",
      accent: "#84cc16",
      banner_url: null,
      logo_url: null,
      layout: "grid",
    },
  },
];

function storeBySlug(slug: string): Store {
  const s = stores.find((x) => x.slug === slug);
  if (!s) throw new Error(`unknown store ${slug}`);
  return s;
}

function img(seed: string): string {
  // Local placeholders (public/seed) so the marketplace renders offline.
  // Real listings will use Cloudflare R2 URLs.
  return `/seed/${seed}.svg`;
}

export const listings: Listing[] = [
  {
    id: "l-denim-jacket",
    store: storeBySlug("the-attic"),
    category_slug: "clothing",
    title: "1980s Faded Levi's Trucker Jacket",
    description:
      "Beautifully broken-in Levi's denim trucker from the early '80s. Genuine fading, no rips, all buttons intact. A true wardrobe staple.",
    price_cents: 8500,
    currency: "usd",
    condition: "Good",
    brand: "Levi's",
    size: "M",
    allow_offers: true,
    min_offer_cents: 6500,
    status: "active",
    images: [img("denim1"), img("denim2")],
    created_at: "2026-06-10T12:00:00Z",
  },
  {
    id: "l-band-tee",
    store: storeBySlug("the-attic"),
    category_slug: "clothing",
    title: "Vintage 1994 Tour Band Tee",
    description:
      "Single-stitch tour tee with authentic wear and a soft, lived-in feel. Front and back graphics in great shape.",
    price_cents: 12000,
    currency: "usd",
    condition: "Worn",
    brand: null,
    size: "L",
    allow_offers: true,
    min_offer_cents: null,
    status: "active",
    images: [img("bandtee1"), img("bandtee2")],
    created_at: "2026-06-12T09:30:00Z",
  },
  {
    id: "l-wool-coat",
    store: storeBySlug("the-attic"),
    category_slug: "clothing",
    title: "Camel Wool Overcoat",
    description: "Timeless camel overcoat in heavyweight wool. Fully lined, classic tailoring.",
    price_cents: 16000,
    currency: "usd",
    condition: "Like New",
    brand: null,
    size: "40R",
    allow_offers: false,
    min_offer_cents: null,
    status: "active",
    images: [img("coat1")],
    created_at: "2026-06-13T15:00:00Z",
  },
  {
    id: "l-jordan-1",
    store: storeBySlug("sole-society"),
    category_slug: "shoes",
    title: "Air Jordan 1 Retro — Chicago",
    description:
      "Iconic colorway in excellent condition. Lightly worn, original box included. A grail for any collection.",
    price_cents: 38000,
    currency: "usd",
    condition: "Like New",
    brand: "Nike",
    size: "US 10",
    allow_offers: true,
    min_offer_cents: 32000,
    status: "active",
    images: [img("jordan1"), img("jordan2"), img("jordan3")],
    created_at: "2026-06-11T18:45:00Z",
  },
  {
    id: "l-adidas-samba",
    store: storeBySlug("sole-society"),
    category_slug: "shoes",
    title: "adidas Samba OG — Vintage Pair",
    description: "Classic gum-sole Sambas with original suede T-toe. Clean uppers, minimal creasing.",
    price_cents: 9500,
    currency: "usd",
    condition: "Good",
    brand: "adidas",
    size: "US 9",
    allow_offers: true,
    min_offer_cents: null,
    status: "active",
    images: [img("samba1")],
    created_at: "2026-06-14T08:15:00Z",
  },
  {
    id: "l-leather-belt",
    store: storeBySlug("the-attic"),
    category_slug: "accessories",
    title: "Hand-Tooled Leather Belt",
    description: "Full-grain leather belt with a solid brass buckle. Develops a gorgeous patina.",
    price_cents: 4200,
    currency: "usd",
    condition: "Good",
    brand: null,
    size: "34",
    allow_offers: true,
    min_offer_cents: 3000,
    status: "active",
    images: [img("belt1")],
    created_at: "2026-06-15T10:00:00Z",
  },
  {
    id: "l-signed-ball",
    store: storeBySlug("the-dugout"),
    category_slug: "memorabilia",
    title: "Signed Official League Baseball",
    description:
      "Authenticated autographed baseball with certificate of authenticity. Display case included.",
    price_cents: 45000,
    currency: "usd",
    condition: "Like New",
    brand: null,
    size: null,
    allow_offers: true,
    min_offer_cents: 38000,
    status: "active",
    images: [img("ball1"), img("ball2")],
    created_at: "2026-06-09T14:20:00Z",
  },
  {
    id: "l-rookie-card",
    store: storeBySlug("the-dugout"),
    category_slug: "memorabilia",
    title: "Graded Rookie Card — Mint 9",
    description: "Professionally graded rookie card, slabbed and protected. A standout for any collection.",
    price_cents: 62000,
    currency: "usd",
    condition: "New",
    brand: null,
    size: null,
    allow_offers: true,
    min_offer_cents: null,
    status: "active",
    images: [img("card1")],
    created_at: "2026-06-16T11:11:00Z",
  },
  {
    id: "l-vinyl-set",
    store: storeBySlug("the-dugout"),
    category_slug: "collectables",
    title: "Rare Pressing Vinyl Bundle",
    description: "A bundle of three rare first-pressing LPs. Sleeves and records in collector-grade shape.",
    price_cents: 14000,
    currency: "usd",
    condition: "Good",
    brand: null,
    size: null,
    allow_offers: true,
    min_offer_cents: 10000,
    status: "active",
    images: [img("vinyl1"), img("vinyl2")],
    created_at: "2026-06-17T16:40:00Z",
  },
  {
    id: "l-comic",
    store: storeBySlug("the-dugout"),
    category_slug: "collectables",
    title: "Vintage Comic — Bagged & Boarded",
    description: "Key issue in well-preserved condition, stored bagged and boarded since purchase.",
    price_cents: 28000,
    currency: "usd",
    condition: "Good",
    brand: null,
    size: null,
    allow_offers: false,
    min_offer_cents: null,
    status: "active",
    images: [img("comic1")],
    created_at: "2026-06-18T13:05:00Z",
  },
];
