-- Self-serve account deletion.
--
-- Apple requires an app that creates accounts to delete them from inside the
-- app (App Store Review Guideline 5.1.1(v)), and the only deletion this
-- codebase had was the superadmin one in src/app/admin/actions.ts -- which
-- refuses outright for any user with orders, listings, authentication requests
-- or registry entries, and tells the admin to suspend instead. That is the
-- right call for a hard delete: most of User's relations have no
-- `onDelete: Cascade`, so `prisma.user.delete` throws, and Order/Listing are
-- the other party's transaction history besides.
--
-- So deletion scrubs the row rather than removing it (see
-- src/lib/deleteAccount.ts). This column is what distinguishes a user who
-- deleted their own account from one an admin suspended -- both end up with
-- `suspended = true`, which is what every existing guard already reads.
--
-- Nullable with no backfill: every existing account is, by definition, not
-- deleted.

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "deletedAt" TIMESTAMP(3);
